# Generated by Django 2.1.2 on 2018-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTele', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbookentry',
            name='email',
            field=models.EmailField(default='example@mail.ru', max_length=255),
        ),
        migrations.AddField(
            model_name='addressbookentry',
            name='komment',
            field=models.TextField(default='Komment'),
        ),
    ]
