# Generated by Django 2.1.2 on 2018-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTele', '0002_auto_20181027_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbookentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='addressbookentry',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
